apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: wordpress
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50